name: natural-events-tracker
channels:
  - conda-forge
  - defaults
dependencies:
  # Python dependencies
  - python=3.11
  - pip
  # Node.js dependencies
  - nodejs=18.*
  - npm
  # Python packages via pip
  - pip:
    - fastapi==0.104.1
    - uvicorn[standard]==0.24.0
    - pydantic==2.5.0
    - httpx==0.25.1
    - python-dotenv==1.0.0
    - redis==5.0.1
    - apscheduler==3.10.4
    - pytest==7.4.3
    - pytest-asyncio==0.21.1
    - black==23.11.0
    - flake8==6.1.0
    - mypy==1.7.0